stages:
  - build
  - manifest

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

.default_docker: &default_docker
  image: docker:27.5.1-cli
  services:
    - name: docker:27.5.1-dind
      alias: docker
      command:
        - --tls=false
        - --host=tcp://0.0.0.0:2375
        - --dns=127.0.0.11
        - --dns=1.1.1.1
  before_script:
    - echo "Runner / Docker info"
    - docker version
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_amd64:
  <<: *default_docker
  stage: build
  tags: ["amd64", "docker"]
  script:
    - echo "Building amd64 image..."
    - docker build --pull --no-cache --provenance=false -t "$IMAGE_NAME:${CI_COMMIT_SHA}-amd64" .
    - docker push "$IMAGE_NAME:${CI_COMMIT_SHA}-amd64"

build_arm64:
  <<: *default_docker
  stage: build
  tags: ["arm64", "docker"]
  script:
    - echo "Building arm64 image..."
    - docker build --pull --no-cache --provenance=false -t "$IMAGE_NAME:${CI_COMMIT_SHA}-arm64" .
    - docker push "$IMAGE_NAME:${CI_COMMIT_SHA}-arm64"

manifest:
  <<: *default_docker
  stage: manifest
  tags: ["amd64", "docker"]
  needs:
    - build_amd64
    - build_arm64
  script:
    - echo "Creating commit manifest..."
    - docker manifest create "$IMAGE_NAME:${CI_COMMIT_SHA}" "$IMAGE_NAME:${CI_COMMIT_SHA}-amd64" "$IMAGE_NAME:${CI_COMMIT_SHA}-arm64"
    - docker manifest push "$IMAGE_NAME:${CI_COMMIT_SHA}"

    - echo "Creating latest manifest..."
    - docker manifest create "$IMAGE_NAME:latest" "$IMAGE_NAME:${CI_COMMIT_SHA}-amd64" "$IMAGE_NAME:${CI_COMMIT_SHA}-arm64"
    - docker manifest push "$IMAGE_NAME:latest"

  only:
    - main
    - master