services:
  url-ip-monitor:
    build: .
    container_name: feedlist
    ports:
      - "8080:8080"
    environment:
      UPDATE_INTERVAL_MINUTES: 60
      DB_PATH: /data/data.db
    volumes:
      - ./data:/data
    restart: unless-stopped

